@startuml
title Add Teacher

' Размещаем акторов вертикально слева
actor "Education Center" as Education Center
actor Teacher 

' Горизонтально располагаем юзкейсы
left to right direction

usecase UC_SendTeacherInfoToCourse as "Send teacher info to course"
usecase UC_ClickAddChild as "Click add child"
usecase UC_EnterInfo as "Enter name, surname, birthdate, Hobby"
usecase UC_Submit as "Click 'Submit'"
usecase UC_Success as "Successful added"

Parent --> UC_ClickAddChild

UC_ClickAddChild --> UC_EnterInfo
UC_EnterInfo --> UC_Submit
UC_Submit --> UC_Success

@enduml