@startuml
title Add Teacher

' Размещаем акторов вертикально слева
actor "Education Center" as EducationCenter
actor Teacher 

' Горизонтально располагаем юзкейсы
left to right direction

usecase UC_AddTeacher as "Add Teacher"
usecase UC_EnterTeacherInfo as "Enter teacher info(Name, Surname, email, subject/course, temp password)"
usecase UC_CreateAccount as "Create account"
usecase UC_SendCredentials as "Send login credentials"
usecase UC_NotifyTeacher as "Notify teacher"

' Связываем акторов с юзкейками
EducationCenter --> UC_AddTeacher

UC_AddTeacher --> UC_EnterTeacherInfo
UC_EnterTeacherInfo --> UC_CreateAccount
UC_CreateAccount --> UC_SendCredentials
UC_SendCredentials --> UC_NotifyTeacher

@enduml